### ISSUE TITLE
Vsync off: fps drops & freezes

### ISSUE THREAD

**Issue by ddurnev** [nvpro-samples/gl_vk_chopper#10]
Running on nvidia 364.16, ubuntu 16.04 x64, GTX Titan X: when vsync is ON it's OK(only minor fps drops sometimes, avg microseconds is 110), but turning vsync off(by pressing 'v' key) causes not only serious fps inconsistencies(avg microseconds changes from 66 to 580), but also freezes GUI(even mouse cursor stops moving).

**Comment by chrisjhebert1973** [comment]
Hi
Are you running this on Windows or Linux? 

I have had some syncronization issues on Linux with chopper which I'm looking into. I've not experienced any issue like this on Windows though

**Comment by ddurnev** [comment]
Sorry, but **ubuntu 16.04 x64** is definitely GNU/Linux system yet :) BTW I don't see any point in using vulkan on Windows, they have DX12 there ;)

**Comment by OlliC** [comment]
Noticed the same on Arch Linux with driver 364.16 and an GTX 660. 

Very stuttery and mouse cursor freezing. I cannot drag the window around or closing it without complete UI freezes for several seconds.

**Comment by Martin-Schultz** [comment]
When i turned off vsync on my windows 10 system there were choppers spawning at 0,0,0
This also happens when vsync is on but it happens way less frequently. with vsync off this happens several times per second.
![chopper1](https://cloud.githubusercontent.com/assets/2989304/15777200/c5d77562-298d-11e6-8198-55ca43a71e8d.jpg)

**Comment by chrisjhebert1973** [comment]
You somehow have a very early version of this sample.
It is no longer called gl_vk_gazelle. This used to happen with the first version when we had an issue with the VkSemaphores. This was fixed several months ago.
