### ISSUE TITLE
Stuttering with vsync off

### ISSUE THREAD

**Issue by kiroma** [nvpro-samples/gl_vk_chopper#12]
On my GTX 950M I am experiencing some weird image stuttering. NSight displays extremely abnormal activity when deactivating vsync (jumping cpu and gpu usage). I've lowered the chopper count in VkeGameRendererDynamic.cpp to 8 but the problem still persists. Also, is the chopper speed supposed to rely on fps count? Because at 200fps they are going at light speed.
Windows 8.1 (x64)

**Comment by chrisjhebert1973** [comment]
I am currently looking into a synchronisation issue that is causing this. As there is already an open issue for this, I am closing this one.
