### ISSUE TITLE
Environment map shows artifacts

### ISSUE THREAD

**Issue by Martin-Schultz** [nvpro-samples/gl_vk_chopper#14]
when i change the view to look more straight downwards, i can see the buttom part of the environment map which seems to be wrong oriented or something else. Anyways i can very clearly see the seams of the cube map textures 
![chopper2](https://cloud.githubusercontent.com/assets/2989304/15777272/379f8a90-298e-11e6-8dab-c5a70c8e85f8.jpg)
 that is used.

**Comment by chrisjhebert1973** [comment]
Where did you get this version from? it's not the version on git hub. That is called 'gl_vk_chopper' not 'gl_vk_gazelle'.

I just checked the cube map on gl_vk_chopper and it has no seams.

I am closing this issue

**Comment by chrisjhebert1973** [comment]
In fact 'gl_vk_gazelle' was never published on github. 
Please can you let me know where you got this sample from?

**Comment by Martin-Schultz** [comment]
I got this sample from the official nvidia Demos page
https://developer.nvidia.com/Vulkan
more specific:
https://nvidia.app.box.com/s/rj9nzxkpz21qu34h8zew301kray9urbf
and this github page is given together with the download.
it is also available from chip.de
http://www.chip.de/downloads/Nvidia-Vulkan-Demo-Choppers_89813533.html

**Comment by chrisjhebert1973** [comment]
Ok. I'll get that changed.
The official NVIDIA demo for this is the one here. gl_vk_chopper.Please download the source and build from github.

**Comment by chrisjhebert1973** [comment]
I have found and updated the chopper build on the NVIDIA site to the latest one.
Please can you test it and verify that it works for you?

**Comment by Martin-Schultz** [comment]
Yes, this Version is way better no issues with vsync, no artifacts in the cube map. You got it all good there. :+1:

**Comment by chrisjhebert1973** [comment]
Awesome!! Glad it's working :-D
