### ISSUE TITLE
Chopper appearing on camera before transform

### ISSUE THREAD

**Issue by AlessandroBorges** [nvpro-samples/gl_vk_chopper#2]
Hi !
On my system (Win10-64, GTX 650 Ti Boost, driver 356,39) seems that each new helicopter appears in front of camera (is it 0,0,0 ?) before it is transformed  and put in correct place .
How it looks :
[Image at GitHub](https://github.com/AlessandroBorges/JGLES-gen/blob/master/Issue-VK%20Chooper.jpg)

**Comment by chrisjhebert1973** [comment]
Hi Alessandro
This has now been fixed, please can you pull down the source again (VkeGameRendererDynamic.h/.cpp) and rebuild.

Regards

Chris Hebert
