### ISSUE TITLE
Don't works with AMD cards.

### ISSUE THREAD

**Issue by sliterok** [nvpro-samples/gl_vk_chopper#3]
Is it my problem, it was planned by nvidia, or it's kinda compatibility problem?

> gl_vk_chopper.exe has stopped working
Happends after device initialization
Using Asus R9 270X and Xeon 1241.

**Comment by chrisjhebert1973** [comment]
Hi Sliterok.

We were unable to test on AMD hardware before the Vulkan launch as we only got access to their drivers yesterday. The sample certainly was put together with NVIDIA hardware in mind. All driver implementations have their own unique features, for example, on NVIDIA hardware we do not 'need' to change image layout like you do on other implementations, (but you do need to transition away from the VK_IMAGE_LAYOUT_UNDEFINED layout when you initially create an image resource). It is the intention that this sample would run with all implementations. As we begin to get access to the other drivers, we will make this so.

Kind Regards

Chris Hebert
