### ISSUE TITLE
Poor performance on GTX 670 w/ i5 3570K @ 4.5 GHz

### ISSUE THREAD

**Issue by zouloum** [nvpro-samples/gl_vk_chopper#4]
Each frame takes about 22 ms to render and my CPU usage is through the roof. 100% of 1 core at all times. GPU usage is also very high (98%)

**Comment by chrisjhebert1973** [comment]
Hi zouloum.
The sample is currently using a single core, this is going to be updated in the next few days, but 100% CPU sounds wrong. I am running this now and it shows 3% which is what it should be. As for the GPU render time, that also seems quite high, it should be around a quarter of that. Cad Scene Threaded and Bk3d show  good examples of multi-threaded rendering, you should look at these ones as well.

I will update you when chopper has been updated with multi threaded features.

Can you send me a screen shot of your CPU usage monitoring so I can investigate this?

Many Thanks

Chris Hebert
NVIDIA

**Comment by chrisjhebert1973** [comment]
Good morning.
There is now an update to vk_gl_chopper. The update really just involves a rework of the chopper geometry which was very high resolution. I now get ~3ms per frame on the GPU with 64 choppers. Please can you let me know how this runs for you.

Many Thanks

Chris Hebert
NVIDIA

**Comment by chrisjhebert1973** [comment]
Good afternoon
There is now another update to gl_vk_chopper. The synchronisation has been improved which should free the CPU up some more.

Many Thanks

Chris Hebert

**Comment by chrisjhebert1973** [comment]
Good evening.
Have you had a chance to retest the latest source? Please could you let me know if this has improved things for you so I can close the issue.

Many Thanks

Chris Hebert
NVIDIA

**Comment by chrisjhebert1973** [comment]
Running fast across Windows, Linux and Tegra.
