### ISSUE TITLE
CreateDevice pNext Field non-NULL?

### ISSUE THREAD

**Issue by mark-lunarg** [nvpro-samples/gl_vk_chopper#5]
Ran this demo with the api_dump layer enabled which resulted in a crash in CreateDevice (or maybe CreateInstance?).  It looked like the pNext field was neither NULL nor a valid pointer to a Vulkan Extension Object.

**Comment by chrisjhebert1973** [comment]
Hi Mark, I've just checked this in debug. Both the VkDeviceCreateInfo and the VkInstanceCreateInfo are correctly zero'd out before they used. Can you provide me with any more information on this. As this would not be the cause of the crash. Are you on Windows or linux?

	/*
		Set up the application create info.
	*/
	VkApplicationInfo appInfo = {VK_STRUCTURE_TYPE_APPLICATION_INFO};
	appInfo.pApplicationName = "gl_vk_chopper";
	appInfo.applicationVersion = 1;
	appInfo.pEngineName = "gl_vk_chopper";
	appInfo.engineVersion = 1;
	appInfo.apiVersion = VK_API_VERSION;
	/*
		Set up the instance create info.
	*/
	VkInstanceCreateInfo createInfo = {VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};
	createInfo.pApplicationInfo = &appInfo;
    createInfo.enabledLayerCount = 0;
	createInfo.ppEnabledLayerNames = NULL;
    createInfo.enabledExtensionCount = 0;
    createInfo.ppEnabledExtensionNames = NULL;


void deviceCreateInfo(
	VkDeviceCreateInfo *outInfo,
	uint32_t inQueueCount,
	VkDeviceQueueCreateInfo *inQueues,
	uint32_t inExtensionCount,
	const char * const * inExtensionNames,
	uint32_t inLayerCount,
	const char * const * inLayerNames,
	VkPhysicalDeviceFeatures *inFeatures
	){

	memset(outInfo, 0, sizeof(VkDeviceCreateInfo));
	outInfo->sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
	outInfo->queueCreateInfoCount= inQueueCount;
	outInfo->pQueueCreateInfos= inQueues;
	outInfo->enabledLayerCount= inLayerCount;
	outInfo->ppEnabledLayerNames = inLayerNames;
	outInfo->enabledExtensionCount = inExtensionCount;
	outInfo->ppEnabledExtensionNames = inExtensionNames;
	outInfo->pEnabledFeatures = inFeatures;

	

}

**Comment by mark-lunarg** [comment]
Yeah, sorry, this was on Windows. Lemme rebuild everything on Master and
run it in the debugger again and I'll post more information (if it repros,
anyway).

Thanks!

**Comment by chrisjhebert1973** [comment]
Ok. In the mean time, I'll check all of the other structures.

**Comment by mark-lunarg** [comment]
Hey Chris,

I figured it out -- it is our deal.  Turns out that there are a couple of
reserved-for-internal-use sTypes --
VK_STRUCTURE_TYPE_LOADER_[DEVICE|INSTANCE]_CREATE_INFO, which are not
correctly handled by the codegen stuff.  This results in api-dump
de-referencing some garbage.  I apologize for the false alarm, and thanks a
bunch for checking out the pCreateInfo contents.

Mark

**Comment by chrisjebert1973** [comment]
No problem Mark.
Glad it’s all good now :-D

Any issues you come across, please let me know.

**Comment by mark-lunarg** [comment]
One more thing, can you take a quick look at pQueueCreateInfos[0].pNext in
CreateDevice? Something doesn't look right but I'm not sure about anything
anymore...


Thanks,
     Mark

**Comment by chrisjebert1973** [comment]
Hi Mark

Just checked the code, and in debug. Looks Ok.

        VkDeviceQueueCreateInfo queueInfo = {};
        queueInfo.queueCount = m_queue_count;
        queueInfo.queueFamilyIndex = 0;
        queueInfo.pQueuePriorities = &priorities;

**Comment by mark-lunarg** [comment]
Hey Chris --

I was able to build and debug the chopper demo here and was unable to get
it to crash for me with the api-dump layer.  That said (and I CANNOT figure
out why) the binary from the website does.  We've been arguing here about
whether initializing a structure with "= {};" always does what we think it
should do in Microsoft C++, or whether it should just be queueInfo{};, but
we don't have any proof either way and both seem to work in our tests.

Can you share which c compiler is used for the sample builds?

Also, queueInfo.sType needs to be
VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO.

Thanks,
     Mark

**Comment by chrisjebert1973** [comment]
Ah, the binary from the website may need an update.
I’m updating the source daily. I’ll get a new binary put up.

The one build from source should run much faster.
