### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by dylanmtaylor** [nvpro-samples/gl_vk_chopper#8]
What are the commands to build this on Linux? The readme is lacking

**Comment by chrisjhebert1973** [comment]
Good Morning. The build process for this is exactly the same as the other samples. You need to pull the sample (along with any others you wish to build), you also need the shared_sources directory (and shared_external if on windows). You run CMake with the nvpro-samples directory as the src directory, it's a good idea to make a completely separate build directory. Once CMake has run, the repsective make files will be in your build directory. CD into the build directory and type 'make'. That's literally it.
